# Generated by Django 2.2.6 on 2019-10-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
